
name: pre-commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set PY
        run: echo "PY=$(python3 -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: python3 -m pip install -r .github/workflows/requirements.txt
      - run: pre-commit install --install-hooks
      - run: pre-commit run --show-diff-on-failure --color=never -a
